// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FdCurrentyDao is the data access object for table fd_currenty.
type FdCurrentyDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns FdCurrentyColumns // columns contains all the column names of Table for convenient usage.
}

// FdCurrentyColumns defines and stores column names for table fd_currenty.
type FdCurrentyColumns struct {
	Code          string // 国家编码
	EnName        string // 国家英文名称
	CnName        string // 国家中文名称
	CurrencyCode  string // 货币编码
	CurrencyCn    string // 货币中文名称
	CurrencyEn    string // 货币英文名称
	Symbol        string // 货币符号
	SymbolNative  string // 货币原生符号
	IsLegalTender string // 是否法定货币：1是，0否
}

// fdCurrentyColumns holds the columns for table fd_currenty.
var fdCurrentyColumns = FdCurrentyColumns{
	Code:          "code",
	EnName:        "en_name",
	CnName:        "cn_name",
	CurrencyCode:  "currency_code",
	CurrencyCn:    "currency_cn",
	CurrencyEn:    "currency_en",
	Symbol:        "symbol",
	SymbolNative:  "symbol_native",
	IsLegalTender: "is_legal_tender",
}

// NewFdCurrentyDao creates and returns a new DAO object for table data access.
func NewFdCurrentyDao() *FdCurrentyDao {
	return &FdCurrentyDao{
		group:   "default",
		table:   "fd_currenty",
		columns: fdCurrentyColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FdCurrentyDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FdCurrentyDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *FdCurrentyDao) Columns() FdCurrentyColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *FdCurrentyDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FdCurrentyDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FdCurrentyDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
