// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. {TplCreatedAtDatetimeStr}
// =================================================================================

package sys_entity

{TplPackageImports}

// {TplTableNameCamelCase} is the golang structure for table {TplTableName}.
{TplStructDefine}
