// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/area"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/auth"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/bizctx"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/captcha"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/casbin"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/fd_account"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/fd_account_bill"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/fd_bank_card"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/fd_currency"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/file"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/jwt"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/middleware"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sdk_aliyun"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sdk_baidu"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sdk_ctyun"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sdk_huawei"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sdk_tencent"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sys_audit"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sys_logs"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sys_menu"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sys_organization"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sys_permission"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sys_role"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sys_sms"
	_ "github.com/SupenBysz/gf-admin-community/internal/logic/sys_user"
)
