// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/utility/daoctl"
	"github.com/SupenBysz/gf-admin-community/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SmsBusinessConfigDao is the data access object for table sms_business_config.
type SmsBusinessConfigDao struct {
	table   string                   // table is the underlying table name of the DAO.
	group   string                   // group is the database configuration group name of current DAO.
	columns SmsBusinessConfigColumns // columns contains all the column names of Table for convenient usage.
}

// SmsBusinessConfigColumns defines and stores column names for table sms_business_config.
type SmsBusinessConfigColumns struct {
	Id           string // ID
	AppNo        string // 应用ID
	BusinessName string // 业务名称
	BusinessNo   string // 业务编号
	TemplateNo   string // 模版编号
	BusinessDesc string // 业务说明
	Remark       string // 备注
	Status       string // 状态
	CreatedAt    string //
	UpdatedAt    string //
	DeletedAt    string //
}

// smsBusinessConfigColumns holds the columns for table sms_business_config.
var smsBusinessConfigColumns = SmsBusinessConfigColumns{
	Id:           "id",
	AppNo:        "app_no",
	BusinessName: "business_name",
	BusinessNo:   "business_no",
	TemplateNo:   "template_no",
	BusinessDesc: "business_desc",
	Remark:       "remark",
	Status:       "status",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
}

// NewSmsBusinessConfigDao creates and returns a new DAO object for table data access.
func NewSmsBusinessConfigDao(proxy ...dao_interface.IDao) *SmsBusinessConfigDao {
	var dao *SmsBusinessConfigDao
	if proxy != nil {
		dao = &SmsBusinessConfigDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: smsBusinessConfigColumns,
		}
		return dao
	}

	return &SmsBusinessConfigDao{
		group:   "default",
		table:   "sms_business_config",
		columns: smsBusinessConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SmsBusinessConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SmsBusinessConfigDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SmsBusinessConfigDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SmsBusinessConfigDao) Columns() SmsBusinessConfigColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SmsBusinessConfigDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SmsBusinessConfigDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SmsBusinessConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
