// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/utility/daoctl"
	"github.com/SupenBysz/gf-admin-community/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SmsAppConfigDao is the data access object for table sms_app_config.
type SmsAppConfigDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns SmsAppConfigColumns // columns contains all the column names of Table for convenient usage.
}

// SmsAppConfigColumns defines and stores column names for table sms_app_config.
type SmsAppConfigColumns struct {
	Id              string // ID
	AppNo           string // 应用编号
	AppName         string // 应用名称
	AvailableNumber string // 可用数量
	CurrentLimiting string // 限流数量
	UseNumber       string // 已用数量
	Remark          string // 备注
	Status          string // 状态
	CreatedAt       string //
	UpdatedAt       string //
	DeletedAt       string //
}

// smsAppConfigColumns holds the columns for table sms_app_config.
var smsAppConfigColumns = SmsAppConfigColumns{
	Id:              "id",
	AppNo:           "app_no",
	AppName:         "app_name",
	AvailableNumber: "available_number",
	CurrentLimiting: "current_limiting",
	UseNumber:       "use_number",
	Remark:          "remark",
	Status:          "status",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	DeletedAt:       "deleted_at",
}

// NewSmsAppConfigDao creates and returns a new DAO object for table data access.
func NewSmsAppConfigDao(proxy ...dao_interface.IDao) *SmsAppConfigDao {
	var dao *SmsAppConfigDao
	if proxy != nil {
		dao = &SmsAppConfigDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: smsAppConfigColumns,
		}
		return dao
	}

	return &SmsAppConfigDao{
		group:   "default",
		table:   "sms_app_config",
		columns: smsAppConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SmsAppConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SmsAppConfigDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SmsAppConfigDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SmsAppConfigDao) Columns() SmsAppConfigColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SmsAppConfigDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SmsAppConfigDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SmsAppConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
