// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/utility/daoctl"
	"github.com/SupenBysz/gf-admin-community/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SmsServiceProviderConfigDao is the data access object for table sms_service_provider_config.
type SmsServiceProviderConfigDao struct {
	table   string                          // table is the underlying table name of the DAO.
	group   string                          // group is the database configuration group name of current DAO.
	columns SmsServiceProviderConfigColumns // columns contains all the column names of Table for convenient usage.
}

// SmsServiceProviderConfigColumns defines and stores column names for table sms_service_provider_config.
type SmsServiceProviderConfigColumns struct {
	Id              string // 渠道商id
	ProviderNo      string // 渠道商编号
	ProviderName    string // 渠道商名字
	AccessKeyId     string // 身份标识
	AccessKeySecret string // 身份认证密钥
	Endpoint        string // 域名调用
	SdkAppId        string // 应用id
	Region          string // 地域
	Remark          string // 备注
	Status          string // 状态
	CreatedAt       string //
	UpdatedAt       string //
	DeletedAt       string //
}

// smsServiceProviderConfigColumns holds the columns for table sms_service_provider_config.
var smsServiceProviderConfigColumns = SmsServiceProviderConfigColumns{
	Id:              "id",
	ProviderNo:      "provider_no",
	ProviderName:    "provider_name",
	AccessKeyId:     "access_key_id",
	AccessKeySecret: "access_key_secret",
	Endpoint:        "endpoint",
	SdkAppId:        "sdk_app_id",
	Region:          "region",
	Remark:          "remark",
	Status:          "status",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	DeletedAt:       "deleted_at",
}

// NewSmsServiceProviderConfigDao creates and returns a new DAO object for table data access.
func NewSmsServiceProviderConfigDao(proxy ...dao_interface.IDao) *SmsServiceProviderConfigDao {
	var dao *SmsServiceProviderConfigDao
	if proxy != nil {
		dao = &SmsServiceProviderConfigDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: smsServiceProviderConfigColumns,
		}
		return dao
	}

	return &SmsServiceProviderConfigDao{
		group:   "default",
		table:   "sms_service_provider_config",
		columns: smsServiceProviderConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SmsServiceProviderConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SmsServiceProviderConfigDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SmsServiceProviderConfigDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SmsServiceProviderConfigDao) Columns() SmsServiceProviderConfigColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SmsServiceProviderConfigDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SmsServiceProviderConfigDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SmsServiceProviderConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
