// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysMenuDao is the data access object for table sys_menu.
type SysMenuDao struct {
	dao_interface.IDao
	table       string         // table is the underlying table name of the DAO.
	group       string         // group is the database configuration group name of current DAO.
	columns     SysMenuColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// SysMenuColumns defines and stores column names for table sys_menu.
type SysMenuColumns struct {
	Id                   string // ID
	Path                 string // 路径
	Name                 string // 名称
	SortTitle            string // 简称
	I18NKey              string // 国际化Key
	Redirect             string // 跳转
	Title                string // 标题
	Icon                 string // 图标
	Layout               string // 布局
	Component            string // 组件
	ParentId             string // 所属父级
	Sort                 string // 排序
	State                string // 状态：1启用，0禁用
	Hidden               string // 是否隐藏：1是，0否
	Description          string // 描述
	IconUrl              string // 图标URL
	RedirectType         string // 跳转类型：1当前页面打开、 2新的标签页打开
	Type                 string // 类型：1菜单、2按钮
	DepPermissionIds     string // 依赖权限Ids
	LimitHiddenRoleIds   string // 限定不可见的角色
	LimitHiddenUserIds   string // 限定不可见的用户
	LimitHiddenUserTypes string // 限定不可见的用户类型
	CreatedAt            string //
	UpdatedAt            string //
}

// sysMenuColumns holds the columns for table sys_menu.
var sysMenuColumns = SysMenuColumns{
	Id:                   "id",
	Path:                 "path",
	Name:                 "name",
	SortTitle:            "sort_title",
	I18NKey:              "i18n_key",
	Redirect:             "redirect",
	Title:                "title",
	Icon:                 "icon",
	Layout:               "layout",
	Component:            "component",
	ParentId:             "parent_id",
	Sort:                 "sort",
	State:                "state",
	Hidden:               "hidden",
	Description:          "description",
	IconUrl:              "icon_url",
	RedirectType:         "redirect_type",
	Type:                 "type",
	DepPermissionIds:     "dep_permission_ids",
	LimitHiddenRoleIds:   "limit_hidden_role_ids",
	LimitHiddenUserIds:   "limit_hidden_user_ids",
	LimitHiddenUserTypes: "limit_hidden_user_types",
	CreatedAt:            "created_at",
	UpdatedAt:            "updated_at",
}

// NewSysMenuDao creates and returns a new DAO object for table data access.
func NewSysMenuDao(proxy ...dao_interface.IDao) *SysMenuDao {
	var dao *SysMenuDao
	if len(proxy) > 0 {
		dao = &SysMenuDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     sysMenuColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &SysMenuDao{
		group:   "default",
		table:   "sys_menu",
		columns: sysMenuColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysMenuDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysMenuDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SysMenuDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SysMenuDao) Columns() SysMenuColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysMenuDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SysMenuDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysMenuDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *SysMenuDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *SysMenuDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *SysMenuDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *SysMenuDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
