// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysIndustryDao is the data access object for table sys_industry.
type SysIndustryDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns SysIndustryColumns // columns contains all the column names of Table for convenient usage.
}

// SysIndustryColumns defines and stores column names for table sys_industry.
type SysIndustryColumns struct {
	Id           string // ID
	CategoryId   string // 行业ID
	CategoryName string // 行业名称
	CategoryDesc string // 行业描述
	Rate         string // 费率
	ParentId     string // 父级ID
	Sort         string // 排序
	State        string // 状态：0隐藏，1显示
	CreatedAt    string //
	UpdatedAt    string //
	DeletedAt    string //
}

// sysIndustryColumns holds the columns for table sys_industry.
var sysIndustryColumns = SysIndustryColumns{
	Id:           "id",
	CategoryId:   "category_id",
	CategoryName: "category_name",
	CategoryDesc: "category_desc",
	Rate:         "rate",
	ParentId:     "parent_id",
	Sort:         "sort",
	State:        "state",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
}

// NewSysIndustryDao creates and returns a new DAO object for table data access.
func NewSysIndustryDao(proxy ...dao_interface.IDao) *SysIndustryDao {
	var dao *SysIndustryDao
	if len(proxy) > 0 {
		dao = &SysIndustryDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: sysIndustryColumns,
		}
		return dao
	}

	return &SysIndustryDao{
		group:   "default",
		table:   "sys_industry",
		columns: sysIndustryColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysIndustryDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysIndustryDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SysIndustryDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SysIndustryDao) Columns() SysIndustryColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysIndustryDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SysIndustryDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysIndustryDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
