// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysAuditDao is the data access object for table sys_audit.
type SysAuditDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns SysAuditColumns // columns contains all the column names of Table for convenient usage.
}

// SysAuditColumns defines and stores column names for table sys_audit.
type SysAuditColumns struct {
	Id            string //
	State         string // 审核状态：-1不通过，0待审核，1通过
	Replay        string // 不通过时回复的审核不通过原因
	UnionMainId   string // 关联业务主体ID：运营商ID、服务商ID、商户ID、消费者ID
	Category      string // 业务类别
	AuditData     string // 待审核的业务数据包
	ExpireAt      string // 服务时限
	AuditReplayAt string // 审核回复时间
	HistoryItems  string // 历史申请记录
	CreatedAt     string //
}

// sysAuditColumns holds the columns for table sys_audit.
var sysAuditColumns = SysAuditColumns{
	Id:            "id",
	State:         "state",
	Replay:        "replay",
	UnionMainId:   "union_main_id",
	Category:      "category",
	AuditData:     "audit_data",
	ExpireAt:      "expire_at",
	AuditReplayAt: "audit_replay_at",
	HistoryItems:  "history_Items",
	CreatedAt:     "created_at",
}

// NewSysAuditDao creates and returns a new DAO object for table data access.
func NewSysAuditDao() *SysAuditDao {
	return &SysAuditDao{
		group:   "default",
		table:   "sys_audit",
		columns: sysAuditColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysAuditDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysAuditDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysAuditDao) Columns() SysAuditColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysAuditDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysAuditDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysAuditDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
