// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysAnnouncementDao is the data access object for table sys_announcement.
type SysAnnouncementDao struct {
	dao_interface.IDao
	table       string                 // table is the underlying table name of the DAO.
	group       string                 // group is the database configuration group name of current DAO.
	columns     SysAnnouncementColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// SysAnnouncementColumns defines and stores column names for table sys_announcement.
type SysAnnouncementColumns struct {
	Id              string //
	Title           string // 公告标题
	UnionMainId     string // 发布主体，0值则代表平台发布的公告
	PublicAt        string // 公示时间，只有到了公示时间用户才可见
	Body            string // 公告正文
	UserTypeScope   string // 受众用户类型：0则所有，复合类型
	ExpireAt        string // 过期时间，过期后前端用户不可见
	State           string // 状态：1草稿、2待发布、4已发布、8已过期、16已撤销
	CreatedAt       string //
	UpdatedAt       string //
	CreatedBy       string // 创建用户
	UpdatedBy       string // 最后修改用户
	DeletedAt       string //
	DeletedBy       string //
	ExtDataJson     string // 扩展json数据
	CategoryId      string // 公告分类ID
	Priority        string // 优先级：1普通、2重要、3紧急
	IsPinned        string // 是否置顶：0否、1是
	IsForceRead     string // 是否强制阅读：0否、1是
	Tags            string // 公告标签，多个用逗号分隔
	ReadCount       string // 阅读次数
	ConfirmRequired string // 是否需要确认：0否、1是
}

// sysAnnouncementColumns holds the columns for table sys_announcement.
var sysAnnouncementColumns = SysAnnouncementColumns{
	Id:              "id",
	Title:           "title",
	UnionMainId:     "union_main_id",
	PublicAt:        "public_at",
	Body:            "body",
	UserTypeScope:   "user_type_scope",
	ExpireAt:        "expire_at",
	State:           "state",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	CreatedBy:       "created_by",
	UpdatedBy:       "updated_by",
	DeletedAt:       "deleted_at",
	DeletedBy:       "deleted_by",
	ExtDataJson:     "ext_data_json",
	CategoryId:      "category_id",
	Priority:        "priority",
	IsPinned:        "is_pinned",
	IsForceRead:     "is_force_read",
	Tags:            "tags",
	ReadCount:       "read_count",
	ConfirmRequired: "confirm_required",
}

// NewSysAnnouncementDao creates and returns a new DAO object for table data access.
func NewSysAnnouncementDao(proxy ...dao_interface.IDao) *SysAnnouncementDao {
	var dao *SysAnnouncementDao
	if len(proxy) > 0 {
		dao = &SysAnnouncementDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     sysAnnouncementColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &SysAnnouncementDao{
		group:   "default",
		table:   "sys_announcement",
		columns: sysAnnouncementColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysAnnouncementDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysAnnouncementDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SysAnnouncementDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SysAnnouncementDao) Columns() SysAnnouncementColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysAnnouncementDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SysAnnouncementDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysAnnouncementDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *SysAnnouncementDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *SysAnnouncementDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *SysAnnouncementDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *SysAnnouncementDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
