// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysInvitePersonDao is the data access object for table sys_invite_person.
type SysInvitePersonDao struct {
	dao_interface.IDao
	table       string                 // table is the underlying table name of the DAO.
	group       string                 // group is the database configuration group name of current DAO.
	columns     SysInvitePersonColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// SysInvitePersonColumns defines and stores column names for table sys_invite_person.
type SysInvitePersonColumns struct {
	Id                      string // ID
	FormUserId              string // 邀请人
	ByUserId                string // 被邀请人
	InviteCode              string // 邀请码
	InviteAt                string // 邀请时间
	UserIdentifierPrefix    string // 用户标识符前缀
	CompanyIdentifierPrefix string // 公司标识符前缀
	InviteId                string // 邀请码ID，来自sys_invite 表
}

// sysInvitePersonColumns holds the columns for table sys_invite_person.
var sysInvitePersonColumns = SysInvitePersonColumns{
	Id:                      "id",
	FormUserId:              "form_user_id",
	ByUserId:                "by_user_id",
	InviteCode:              "invite_code",
	InviteAt:                "invite_at",
	UserIdentifierPrefix:    "user_identifier_prefix",
	CompanyIdentifierPrefix: "company_identifier_prefix",
	InviteId:                "invite_id",
}

// NewSysInvitePersonDao creates and returns a new DAO object for table data access.
func NewSysInvitePersonDao(proxy ...dao_interface.IDao) *SysInvitePersonDao {
	var dao *SysInvitePersonDao
	if len(proxy) > 0 {
		dao = &SysInvitePersonDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     sysInvitePersonColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &SysInvitePersonDao{
		group:   "default",
		table:   "sys_invite_person",
		columns: sysInvitePersonColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysInvitePersonDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysInvitePersonDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SysInvitePersonDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SysInvitePersonDao) Columns() SysInvitePersonColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysInvitePersonDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SysInvitePersonDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysInvitePersonDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *SysInvitePersonDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *SysInvitePersonDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *SysInvitePersonDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *SysInvitePersonDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
