// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysMemberLevelDao is the data access object for table sys_member_level.
type SysMemberLevelDao struct {
	dao_interface.IDao
	table       string                // table is the underlying table name of the DAO.
	group       string                // group is the database configuration group name of current DAO.
	columns     SysMemberLevelColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// SysMemberLevelColumns defines and stores column names for table sys_member_level.
type SysMemberLevelColumns struct {
	Id          string // ID
	Name        string // 名称
	Desc        string // 描述
	Identifier  string // 级别标识符
	CreatedAt   string //
	UpdatedAt   string //
	CreatedBy   string //
	UnionMainId string //
	Level       string // 权益级别，要遵循数值越大，权益越多
}

// sysMemberLevelColumns holds the columns for table sys_member_level.
var sysMemberLevelColumns = SysMemberLevelColumns{
	Id:          "id",
	Name:        "name",
	Desc:        "desc",
	Identifier:  "identifier",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	CreatedBy:   "created_by",
	UnionMainId: "union_main_id",
	Level:       "level",
}

// NewSysMemberLevelDao creates and returns a new DAO object for table data access.
func NewSysMemberLevelDao(proxy ...dao_interface.IDao) *SysMemberLevelDao {
	var dao *SysMemberLevelDao
	if len(proxy) > 0 {
		dao = &SysMemberLevelDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     sysMemberLevelColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &SysMemberLevelDao{
		group:   "default",
		table:   "sys_member_level",
		columns: sysMemberLevelColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysMemberLevelDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysMemberLevelDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SysMemberLevelDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SysMemberLevelDao) Columns() SysMemberLevelColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysMemberLevelDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SysMemberLevelDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysMemberLevelDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *SysMemberLevelDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *SysMemberLevelDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *SysMemberLevelDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *SysMemberLevelDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
