// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysCategoryDao is the data access object for table sys_category.
type SysCategoryDao struct {
	dao_interface.IDao
	table       string             // table is the underlying table name of the DAO.
	group       string             // group is the database configuration group name of current DAO.
	columns     SysCategoryColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// SysCategoryColumns defines and stores column names for table sys_category.
type SysCategoryColumns struct {
	Id          string //
	Name        string // 名称
	ParentId    string // 父级ID
	PicturePath string // 分类图片
	Hidden      string // 是否隐藏
	Sort        string // 顺序
	UnionMainId string // 关联主体ID（保留字段）
	Description string // 描述
}

// sysCategoryColumns holds the columns for table sys_category.
var sysCategoryColumns = SysCategoryColumns{
	Id:          "id",
	Name:        "name",
	ParentId:    "parent_id",
	PicturePath: "picture_path",
	Hidden:      "hidden",
	Sort:        "sort",
	UnionMainId: "union_main_id",
	Description: "description",
}

// NewSysCategoryDao creates and returns a new DAO object for table data access.
func NewSysCategoryDao(proxy ...dao_interface.IDao) *SysCategoryDao {
	var dao *SysCategoryDao
	if len(proxy) > 0 {
		dao = &SysCategoryDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     sysCategoryColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &SysCategoryDao{
		group:   "default",
		table:   "sys_category",
		columns: sysCategoryColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysCategoryDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysCategoryDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SysCategoryDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SysCategoryDao) Columns() SysCategoryColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysCategoryDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SysCategoryDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysCategoryDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *SysCategoryDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *SysCategoryDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *SysCategoryDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *SysCategoryDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
