// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysAnnouncementCategoryDao is the data access object for table sys_announcement_category.
type SysAnnouncementCategoryDao struct {
	dao_interface.IDao
	table       string                         // table is the underlying table name of the DAO.
	group       string                         // group is the database configuration group name of current DAO.
	columns     SysAnnouncementCategoryColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// SysAnnouncementCategoryColumns defines and stores column names for table sys_announcement_category.
type SysAnnouncementCategoryColumns struct {
	Id          string //
	Name        string // 分类名称
	Code        string // 分类编码
	UnionMainId string // 所属主体ID
	Sort        string // 排序
	Description string // 描述
	CreatedAt   string //
	UpdatedAt   string //
	CreatedBy   string //
	UpdatedBy   string //
	DeletedAt   string //
	DeletedBy   string //
}

// sysAnnouncementCategoryColumns holds the columns for table sys_announcement_category.
var sysAnnouncementCategoryColumns = SysAnnouncementCategoryColumns{
	Id:          "id",
	Name:        "name",
	Code:        "code",
	UnionMainId: "union_main_id",
	Sort:        "sort",
	Description: "description",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	CreatedBy:   "created_by",
	UpdatedBy:   "updated_by",
	DeletedAt:   "deleted_at",
	DeletedBy:   "deleted_by",
}

// NewSysAnnouncementCategoryDao creates and returns a new DAO object for table data access.
func NewSysAnnouncementCategoryDao(proxy ...dao_interface.IDao) *SysAnnouncementCategoryDao {
	var dao *SysAnnouncementCategoryDao
	if len(proxy) > 0 {
		dao = &SysAnnouncementCategoryDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     sysAnnouncementCategoryColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &SysAnnouncementCategoryDao{
		group:   "default",
		table:   "sys_announcement_category",
		columns: sysAnnouncementCategoryColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysAnnouncementCategoryDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysAnnouncementCategoryDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SysAnnouncementCategoryDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SysAnnouncementCategoryDao) Columns() SysAnnouncementCategoryColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysAnnouncementCategoryDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SysAnnouncementCategoryDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysAnnouncementCategoryDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *SysAnnouncementCategoryDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *SysAnnouncementCategoryDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *SysAnnouncementCategoryDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *SysAnnouncementCategoryDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
