// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysInviteDao is the data access object for table sys_invite.
type SysInviteDao struct {
	dao_interface.IDao
	table       string           // table is the underlying table name of the DAO.
	group       string           // group is the database configuration group name of current DAO.
	columns     SysInviteColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// SysInviteColumns defines and stores column names for table sys_invite.
type SysInviteColumns struct {
	Id             string // ID
	UserId         string // 用户ID, 也就是邀约人ID
	Value          string // 邀约码背后的关联业务Json数据,
	ExpireAt       string // 邀约码的过期失效
	ActivateNumber string // 邀约码的激活次数限制
	State          string // 状态： 0失效、1正常
	Type           string // 类型： 1注册、2加入团队、4加入角色 (复合类型)
	CreatedAt      string //
}

// sysInviteColumns holds the columns for table sys_invite.
var sysInviteColumns = SysInviteColumns{
	Id:             "id",
	UserId:         "user_id",
	Value:          "value",
	ExpireAt:       "expire_at",
	ActivateNumber: "activate_number",
	State:          "state",
	Type:           "type",
	CreatedAt:      "created_at",
}

// NewSysInviteDao creates and returns a new DAO object for table data access.
func NewSysInviteDao(proxy ...dao_interface.IDao) *SysInviteDao {
	var dao *SysInviteDao
	if len(proxy) > 0 {
		dao = &SysInviteDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     sysInviteColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &SysInviteDao{
		group:   "default",
		table:   "sys_invite",
		columns: sysInviteColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysInviteDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysInviteDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SysInviteDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SysInviteDao) Columns() SysInviteColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysInviteDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SysInviteDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysInviteDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *SysInviteDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *SysInviteDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *SysInviteDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *SysInviteDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
