// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysUserDetailDao is the data access object for table sys_user_detail.
type SysUserDetailDao struct {
	dao_interface.IDao
	table       string               // table is the underlying table name of the DAO.
	group       string               // group is the database configuration group name of current DAO.
	columns     SysUserDetailColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// SysUserDetailColumns defines and stores column names for table sys_user_detail.
type SysUserDetailColumns struct {
	Id              string // ID，保持与USERID一致
	Realname        string // 姓名
	UnionMainName   string // 关联主体名称
	LastLoginIp     string // 最后登录IP
	LastLoginArea   string // 最后登录地区
	LastLoginAt     string // 最后登录时间
	LastHeartbeatAt string // 最后在线时间
}

// sysUserDetailColumns holds the columns for table sys_user_detail.
var sysUserDetailColumns = SysUserDetailColumns{
	Id:              "id",
	Realname:        "realname",
	UnionMainName:   "union_main_name",
	LastLoginIp:     "last_login_ip",
	LastLoginArea:   "last_login_area",
	LastLoginAt:     "last_login_at",
	LastHeartbeatAt: "last_heartbeat_at",
}

// NewSysUserDetailDao creates and returns a new DAO object for table data access.
func NewSysUserDetailDao(proxy ...dao_interface.IDao) *SysUserDetailDao {
	var dao *SysUserDetailDao
	if len(proxy) > 0 {
		dao = &SysUserDetailDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     sysUserDetailColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &SysUserDetailDao{
		group:   "default",
		table:   "sys_user_detail",
		columns: sysUserDetailColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysUserDetailDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysUserDetailDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SysUserDetailDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SysUserDetailDao) Columns() SysUserDetailColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysUserDetailDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SysUserDetailDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysUserDetailDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *SysUserDetailDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *SysUserDetailDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *SysUserDetailDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *SysUserDetailDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
