// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/model"
	"github.com/SupenBysz/gf-admin-community/model/entity"
)

type (
	IFdAccount interface {
		CreateFdAccount(ctx context.Context, info model.FdAccountRegister) (*entity.FdAccount, error)
		GetAccountById(ctx context.Context, id int64) (*entity.FdAccount, error)
		UpdateFdAccountIsEnable(ctx context.Context, id int64, isEnabled int64) (bool, error)
		HasAccountByName(ctx context.Context, name string) (*entity.FdAccount, error)
	}
)

var (
	localFdAccount IFdAccount
)

func FdAccount() IFdAccount {
	if localFdAccount == nil {
		panic("implement not found for interface IFdAccount, forgot register?")
	}
	return localFdAccount
}

func RegisterFdAccount(i IFdAccount) {
	localFdAccount = i
}
