// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/model"
)

type (
	IFdAccountBill interface {
		CreateAccountBill(ctx context.Context, info model.AccountBillRegister) (bool, error)
	}
)

var (
	localFdAccountBill IFdAccountBill
)

func FdAccountBill() IFdAccountBill {
	if localFdAccountBill == nil {
		panic("implement not found for interface IFdAccountBill, forgot register?")
	}
	return localFdAccountBill
}

func RegisterFdAccountBill(i IFdAccountBill) {
	localFdAccountBill = i
}
