// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/model"
	"github.com/SupenBysz/gf-admin-community/model/entity"
)

type (
	IFdInvoice interface {
		CreateInvoice(ctx context.Context, info model.FdInvoiceRegister) (*entity.FdInvoice, error)
		GetInvoiceById(ctx context.Context, id int64) (*entity.FdInvoice, error)
		GetInvoiceList(ctx context.Context, info *model.SearchParams, userId int64) (*model.FdInvoiceListRes, error)
	}
)

var (
	localFdInvoice IFdInvoice
)

func FdInvoice() IFdInvoice {
	if localFdInvoice == nil {
		panic("implement not found for interface IFdInvoice, forgot register?")
	}
	return localFdInvoice
}

func RegisterFdInvoice(i IFdInvoice) {
	localFdInvoice = i
}
