// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/model"
	"github.com/SupenBysz/gf-admin-community/model/entity"
	kyEnum "github.com/SupenBysz/gf-admin-community/model/enum"
)

type (
	IFile interface {
		InstallHook(state kyEnum.UploadEventState, hookFunc model.FileHookFunc) int64
		UnInstallHook(savedHookId int64)
		CleanAllHook()
		Upload(ctx context.Context, in model.FileUploadInput, userId int64) (*model.FileUploadOutput, error)
		GetUploadFile(ctx context.Context, uploadId int64, userId int64, message ...string) (*model.FileUploadOutput, error)
		SaveFile(ctx context.Context, storageAddr string, userId int64, info model.FileUploadOutput) (*entity.SysFile, error)
		UploadIDCard(ctx context.Context, in model.OCRIDCardFileUploadInput, userId int64) (*model.IDCardWithOCR, error)
		UploadBankCard(ctx context.Context, in model.BankCardWithOCRInput, userId int64) (*model.BankCardWithOCR, error)
		UploadBusinessLicense(ctx context.Context, in model.OCRBusinessLicense, userId int64) (*model.BusinessLicenseWithOCR, error)
		DownLoadFile(ctx context.Context, savePath string, url string) (string, error)
	}
)

var (
	localFile IFile
)

func File() IFile {
	if localFile == nil {
		panic("implement not found for interface IFile, forgot register?")
	}
	return localFile
}

func RegisterFile(i IFile) {
	localFile = i
}
