// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/model"
)

type (
	ISdkCtyun interface {
		GetCtyunSdkConfList(ctx context.Context) (*[]model.CtyunSdkConf, error)
		GetCtyunSdkConf(ctx context.Context, identifier string) (tokenInfo *model.CtyunSdkConf, err error)
		SaveCtyunSdkConf(ctx context.Context, info model.CtyunSdkConf, isCreate bool) (*model.CtyunSdkConf, error)
		DeleteCtyunSdkConf(ctx context.Context, identifier string) (bool, error)
	}
)

var (
	localSdkCtyun ISdkCtyun
)

func SdkCtyun() ISdkCtyun {
	if localSdkCtyun == nil {
		panic("implement not found for interface ISdkCtyun, forgot register?")
	}
	return localSdkCtyun
}

func RegisterSdkCtyun(i ISdkCtyun) {
	localSdkCtyun = i
}
