// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/api_v1/sysapi"
	"github.com/SupenBysz/gf-admin-community/model"
	"github.com/SupenBysz/gf-admin-community/model/entity"
)

type (
	ISysOrganization interface {
		QueryOrganizationList(ctx context.Context, info model.SearchParams) (*sysapi.OrganizationInfoListRes, error)
		GetOrganizationList(ctx context.Context, parentId int64, IsRecursive bool) (*[]entity.SysOrganization, int, error)
		GetOrganizationTree(ctx context.Context, parentId int64) (*[]model.SysOrganizationTree, error)
		CreateOrganizationInfo(ctx context.Context, info model.SysOrganizationInfo) (*entity.SysOrganization, error)
		UpdateOrganizationInfo(ctx context.Context, info model.SysOrganizationInfo) (*entity.SysOrganization, error)
		SaveOrganizationInfo(ctx context.Context, info model.SysOrganizationInfo) (*entity.SysOrganization, error)
		GetOrganizationInfo(ctx context.Context, id int64) (*entity.SysOrganization, error)
		DeleteOrganizationInfo(ctx context.Context, id int64) (bool, error)
	}
)

var (
	localSysOrganization ISysOrganization
)

func SysOrganization() ISysOrganization {
	if localSysOrganization == nil {
		panic("implement not found for interface ISysOrganization, forgot register?")
	}
	return localSysOrganization
}

func RegisterSysOrganization(i ISysOrganization) {
	localSysOrganization = i
}
