// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsAppConfig is the golang structure for table sms_app_config.
type SmsAppConfig struct {
	Id              int64       `json:"id"              description:"ID"`
	AppNo           string      `json:"appNo"           description:"应用编号"`
	AppName         string      `json:"appName"         description:"应用名称"`
	AvailableNumber int         `json:"availableNumber" description:"可用数量"`
	CurrentLimiting int         `json:"currentLimiting" description:"限流数量"`
	UseNumber       int         `json:"useNumber"       description:"已用数量"`
	Remark          string      `json:"remark"          description:"备注"`
	Status          int         `json:"status"          description:"状态"`
	CreatedAt       *gtime.Time `json:"createdAt"       description:""`
	UpdatedAt       *gtime.Time `json:"updatedAt"       description:""`
	DeletedAt       *gtime.Time `json:"deletedAt"       description:""`
}
