// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsBusinessConfig is the golang structure for table sms_business_config.
type SmsBusinessConfig struct {
	Id           int64       `json:"id"           description:"ID"`
	AppNo        string      `json:"appNo"        description:"应用ID"`
	BusinessName string      `json:"businessName" description:"业务名称"`
	BusinessNo   string      `json:"businessNo"   description:"业务编号"`
	TemplateNo   string      `json:"templateNo"   description:"模版编号"`
	BusinessDesc string      `json:"businessDesc" description:"业务说明"`
	Remark       string      `json:"remark"       description:"备注"`
	Status       int         `json:"status"       description:"状态"`
	CreatedAt    *gtime.Time `json:"createdAt"    description:""`
	UpdatedAt    *gtime.Time `json:"updatedAt"    description:""`
	DeletedAt    *gtime.Time `json:"deletedAt"    description:""`
}
