// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsServiceProviderConfig is the golang structure for table sms_service_provider_config.
type SmsServiceProviderConfig struct {
	Id              int64       `json:"id"              description:"渠道商id"`
	ProviderNo      string      `json:"providerNo"      description:"渠道商编号"`
	ProviderName    string      `json:"providerName"    description:"渠道商名字"`
	AccessKeyId     string      `json:"accessKeyId"     description:"身份标识"`
	AccessKeySecret string      `json:"accessKeySecret" description:"身份认证密钥"`
	Endpoint        string      `json:"endpoint"        description:"域名调用"`
	SdkAppId        string      `json:"sdkAppId"        description:"应用id"`
	Region          string      `json:"region"          description:"地域"`
	Remark          string      `json:"remark"          description:"备注"`
	Status          int         `json:"status"          description:"状态: 0禁用 1正常"`
	CreatedAt       *gtime.Time `json:"createdAt"       description:""`
	UpdatedAt       *gtime.Time `json:"updatedAt"       description:""`
	DeletedAt       *gtime.Time `json:"deletedAt"       description:""`
}
