// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsSignConfig is the golang structure for table sms_sign_config.
type SmsSignConfig struct {
	Id           int64       `json:"id"           description:"ID"`
	SignName     string      `json:"signName"     description:"短信签名名称"`
	ProviderNo   string      `json:"providerNo"   description:"渠道商编号"`
	ProviderName string      `json:"providerName" description:"渠道商名字"`
	Remark       string      `json:"remark"       description:"备注"`
	Status       int         `json:"status"       description:"状态"`
	CreatedAt    *gtime.Time `json:"createdAt"    description:""`
	UpdatedAt    *gtime.Time `json:"updatedAt"    description:""`
	DeletedAt    *gtime.Time `json:"deletedAt"    description:""`
}
