// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsSendLog is the golang structure for table sms_send_log.
type SmsSendLog struct {
	Id          int64       `json:"id"          description:"ID"`
	AppNo       string      `json:"appNo"       description:"应用ID"`
	BusinessNo  string      `json:"businessNo"  description:"业务编号"`
	Status      int         `json:"status"      description:"状态"`
	Fee         string      `json:"fee"         description:"计价条数"`
	PhoneNumber string      `json:"phoneNumber" description:"发送手机号"`
	Message     string      `json:"message"     description:"接口响应消息"`
	Code        string      `json:"code"        description:"接口响应状态码"`
	Content     string      `json:"content"     description:"发送内容"`
	Remark      string      `json:"remark"      description:"备注"`
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:""`
	DeletedAt   *gtime.Time `json:"deletedAt"   description:""`
}
