// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysPermission is the golang structure for table sys_permission.
type SysPermission struct {
	Id          int64       `json:"id"          description:"ID"`
	ParentId    int64       `json:"parentId"    description:"父级ID"`
	Name        string      `json:"name"        description:"名称"`
	Description string      `json:"description" description:"描述"`
	Identifier  string      `json:"identifier"  description:"标识符"`
	Type        int         `json:"type"        description:"类型：1api，2menu"`
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:""`
	IsShow      int         `json:"isShow"      description:"是否显示：0不显示 1显示"`
}
