// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysMessage is the golang structure for table sys_message.
type SysMessage struct {
	Id             int64       `json:"id"             description:"ID"`
	Title          string      `json:"title"          description:"标题"`
	Summary        string      `json:"summary"        description:"摘要"`
	Content        string      `json:"content"        description:"内容"`
	Type           int         `json:"type"           description:"消息类型"`
	Link           string      `json:"link"           description:"跳转链接"`
	ToUserIds      string      `json:"toUserIds"      description:"接收者UserIds，允许有多个接收者"`
	ToUserType     int         `json:"toUserType"     description:"接收者类型用户类型，和UserType保持一致"`
	FromUserId     int64       `json:"fromUserId"     description:"发送者ID，为-1代表系统消息"`
	FromUserType   int         `json:"fromUserType"   description:"发送者类型"`
	SendAt         *gtime.Time `json:"sendAt"         description:"发送时间"`
	ExtJson        string      `json:"extJson"        description:"拓展数据Json"`
	ReadUserIds    string      `json:"readUserIds"    description:"已读用户UserIds"`
	DataIdentifier string      `json:"dataIdentifier" description:"关联的数据标识"`
	CreatedAt      *gtime.Time `json:"createdAt"      description:""`
	UpdatedAt      *gtime.Time `json:"updatedAt"      description:""`
	DeletedAt      *gtime.Time `json:"deletedAt"      description:""`
}
