// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysPersonLicense is the golang structure for table sys_person_license.
type SysPersonLicense struct {
	Id               int64       `json:"id"               description:"ID"`
	IdcardFrontPath  string      `json:"idcardFrontPath"  description:"身份证头像面照片"`
	IdcardBackPath   string      `json:"idcardBackPath"   description:"身份证国徽面照片"`
	No               string      `json:"no"               description:"身份证号"`
	Gender           int         `json:"gender"           description:"性别"`
	Nation           string      `json:"nation"           description:"名族"`
	Name             string      `json:"name"             description:"姓名"`
	Birthday         string      `json:"birthday"         description:"出生日期"`
	Address          string      `json:"address"          description:"家庭住址"`
	IssuingAuthorit  string      `json:"issuingAuthorit"  description:"签发机关"`
	IssuingDate      string      `json:"issuingDate"      description:"签发日期"`
	ExpriyDate       string      `json:"expriyDate"       description:""`
	CreatedAt        *gtime.Time `json:"createdAt"        description:""`
	UpdatedAt        *gtime.Time `json:"updatedAt"        description:""`
	DeletedAt        *gtime.Time `json:"deletedAt"        description:""`
	State            int         `json:"state"            description:"状态"`
	AuthType         int         `json:"authType"         description:"认证类型:"`
	Remark           string      `json:"remark"           description:"备注信息"`
	LatestAuditLogId int64       `json:"latestAuditLogId" description:"最新的审核记录id"`
}
