// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysInvite is the golang structure for table sys_invite.
type SysInvite struct {
	Id             int64       `json:"id"             description:"ID"`
	UserId         int64       `json:"userId"         description:"用户ID, 也就是邀约人ID"`
	Value          string      `json:"value"          description:"邀约码背后的关联业务Json数据,"`
	ExpireAt       *gtime.Time `json:"expireAt"       description:"邀约码的过期失效"`
	ActivateNumber int         `json:"activateNumber" description:"邀约码的激活次数限制"`
	State          int         `json:"state"          description:"状态： 0失效、1正常"`
	Type           int         `json:"type"           description:"类型： 1注册、2加入团队、4加入角色 (复合类型)"`
	CreatedAt      *gtime.Time `json:"createdAt"      description:""`
}
