// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

// SysArea is the golang structure for table sys_area.
type SysArea struct {
	Id            int64  `json:"id"            description:"ID"`
	AreaCode      int    `json:"areaCode"      description:"地区编码"`
	AreaName      string `json:"areaName"      description:"地区名称"`
	Level         int    `json:"level"         description:"1:省份province,2:市city,3:区县district,4:街道street"`
	CityCode      string `json:"cityCode"      description:"城市编码"`
	LatLongCenter string `json:"latLongCenter" description:"城市中心点（即经纬度）"`
	ParentId      int64  `json:"parentId"      description:"地区父节点"`
}
