// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FdAccount is the golang structure of table fd_account for DAO operations like Where/Data.
type FdAccount struct {
	g.Meta             `orm:"table:fd_account, do:true"`
	Id                 interface{} // ID
	Name               interface{} // 账户名称
	UnionLicenseId     interface{} // 关联资质ID，大于0时必须保值与 union_user_id 关联得上
	UnionUserId        interface{} // 关联用户ID
	CurrencyCode       interface{} // 货币代码
	IsEnabled          interface{} // 是否启用：1启用，0禁用
	LimitState         interface{} // 限制状态：0不限制，1限制支出、2限制收入
	PrecisionOfBalance interface{} // 货币单位精度：1:元，10:角，100:分，1000:厘，10000:毫，……
	Balance            interface{} // 当前余额，必须要与账单最后一笔交易余额对应得上
	CreatedAt          *gtime.Time //
	UpdatedAt          *gtime.Time //
	DeletedAt          *gtime.Time //
	Version            interface{} // 乐观锁所需数据版本字段
}
