// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FdInvoice is the golang structure of table fd_invoice for DAO operations like Where/Data.
type FdInvoice struct {
	g.Meta         `orm:"table:fd_invoice, do:true"`
	Id             interface{} //
	Name           interface{} // 发票抬头名称
	TaxId          interface{} // 纳税识别号
	Addr           interface{} // 发票收件地址，限纸质
	Email          interface{} // 发票收件邮箱，限电子发票
	UserId         interface{} // 申请人UserID
	AuditUserId    interface{} // 审核人UserID
	AuditReplayMsg interface{} // 审核回复，仅审核不通过时才有值
	AuditAt        *gtime.Time // 审核时间
	State          interface{} // 状态：0待审核、1已通过、-1不通过
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
	DeletedAt      *gtime.Time //
}
