// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysMenu is the golang structure of table sys_menu for DAO operations like Where/Data.
type SysMenu struct {
	g.Meta      `orm:"table:sys_menu, do:true"`
	Id          interface{} // ID
	Path        interface{} // 路径
	Name        interface{} // 名称
	Redirect    interface{} // 跳转
	Title       interface{} // 标题
	Icon        interface{} // 图标
	Component   interface{} // 组件
	ParentId    interface{} // 所属父级
	Sort        interface{} // 排序
	State       interface{} // 状态：0隐藏，1显示
	Description interface{} // 描述
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
