// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
)

// internalSmsServiceProviderConfigDao is internal type for wrapping internal DAO implements.
type internalSmsServiceProviderConfigDao = *internal.SmsServiceProviderConfigDao

// smsServiceProviderConfigDao is the data access object for table sms_service_provider_config.
// You can define custom methods on it to extend its functionality as you wish.
type smsServiceProviderConfigDao struct {
	internalSmsServiceProviderConfigDao
}

var (
	// SmsServiceProviderConfig is globally public accessible object for table sms_service_provider_config operations.
	SmsServiceProviderConfig = smsServiceProviderConfigDao{
		internal.NewSmsServiceProviderConfigDao(),
	}
)

// Fill with you ideas below.
