// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
)

// internalSmsSendLogDao is internal type for wrapping internal DAO implements.
type internalSmsSendLogDao = *internal.SmsSendLogDao

// smsSendLogDao is the data access object for table sms_send_log.
// You can define custom methods on it to extend its functionality as you wish.
type smsSendLogDao struct {
	internalSmsSendLogDao
}

var (
	// SmsSendLog is globally public accessible object for table sms_send_log operations.
	SmsSendLog = smsSendLogDao{
		internal.NewSmsSendLogDao(),
	}
)

// Fill with you ideas below.
