// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
)

// internalSmsBusinessConfigDao is internal type for wrapping internal DAO implements.
type internalSmsBusinessConfigDao = *internal.SmsBusinessConfigDao

// smsBusinessConfigDao is the data access object for table sms_business_config.
// You can define custom methods on it to extend its functionality as you wish.
type smsBusinessConfigDao struct {
	internalSmsBusinessConfigDao
}

var (
	// SmsBusinessConfig is globally public accessible object for table sms_business_config operations.
	SmsBusinessConfig = smsBusinessConfigDao{
		internal.NewSmsBusinessConfigDao(),
	}
)

// Fill with you ideas below.
