// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
)

// internalSmsTemplateConfigDao is internal type for wrapping internal DAO implements.
type internalSmsTemplateConfigDao = *internal.SmsTemplateConfigDao

// smsTemplateConfigDao is the data access object for table sms_template_config.
// You can define custom methods on it to extend its functionality as you wish.
type smsTemplateConfigDao struct {
	internalSmsTemplateConfigDao
}

var (
	// SmsTemplateConfig is globally public accessible object for table sms_template_config operations.
	SmsTemplateConfig = smsTemplateConfigDao{
		internal.NewSmsTemplateConfigDao(),
	}
)

// Fill with you ideas below.
