// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
)

// internalSmsSignConfigDao is internal type for wrapping internal DAO implements.
type internalSmsSignConfigDao = *internal.SmsSignConfigDao

// smsSignConfigDao is the data access object for table sms_sign_config.
// You can define custom methods on it to extend its functionality as you wish.
type smsSignConfigDao struct {
	internalSmsSignConfigDao
}

var (
	// SmsSignConfig is globally public accessible object for table sms_sign_config operations.
	SmsSignConfig = smsSignConfigDao{
		internal.NewSmsSignConfigDao(),
	}
)

// Fill with you ideas below.
