// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
)

// internalSmsAppConfigDao is internal type for wrapping internal DAO implements.
type internalSmsAppConfigDao = *internal.SmsAppConfigDao

// smsAppConfigDao is the data access object for table sms_app_config.
// You can define custom methods on it to extend its functionality as you wish.
type smsAppConfigDao struct {
	internalSmsAppConfigDao
}

var (
	// SmsAppConfig is globally public accessible object for table sms_app_config operations.
	SmsAppConfig = smsAppConfigDao{
		internal.NewSmsAppConfigDao(),
	}
)

// Fill with you ideas below.
