// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
)

type SysDeliveryDao = dao_interface.TIDao[internal.SysDeliveryColumns]

func NewSysDelivery(dao ...dao_interface.IDao) SysDeliveryDao {
	return (SysDeliveryDao)(internal.NewSysDeliveryDao(dao...))
}

var (
	SysDelivery = NewSysDelivery()
)
