// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
)

// internalSysPermissionDao is internal type for wrapping internal DAO implements.
type internalSysPermissionDao = *internal.SysPermissionDao

// sysPermissionDao is the data access object for table sys_permission.
// You can define custom methods on it to extend its functionality as you wish.
type sysPermissionDao struct {
	internalSysPermissionDao
}

var (
	// SysPermission is globally public accessible object for table sys_permission operations.
	SysPermission = sysPermissionDao{
		internal.NewSysPermissionDao(),
	}
)

// Fill with you ideas below.
