// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
)

type SysAnnouncementConfirmDao = dao_interface.TIDao[internal.SysAnnouncementConfirmColumns]

func NewSysAnnouncementConfirm(dao ...dao_interface.IDao) SysAnnouncementConfirmDao {
	return (SysAnnouncementConfirmDao)(internal.NewSysAnnouncementConfirmDao(dao...))
}

var (
	SysAnnouncementConfirm = NewSysAnnouncementConfirm()
)
