// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
)

type SysPersonLicenseDao = dao_interface.TIDao[internal.SysPersonLicenseColumns]

func NewSysPersonLicense(dao ...dao_interface.IDao) SysPersonLicenseDao {
	return (SysPersonLicenseDao)(internal.NewSysPersonLicenseDao(dao...))
}

var (
	SysPersonLicense = NewSysPersonLicense()
)
