// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
)

// internalSysPersonAuditDao is internal type for wrapping internal DAO implements.
type internalSysPersonAuditDao = *internal.SysPersonAuditDao

// sysPersonAuditDao is the data access object for table sys_person_audit.
// You can define custom methods on it to extend its functionality as you wish.
type sysPersonAuditDao struct {
	internalSysPersonAuditDao
}

var (
	// SysPersonAudit is globally public accessible object for table sys_person_audit operations.
	SysPersonAudit = sysPersonAuditDao{
		internal.NewSysPersonAuditDao(),
	}
)

// Fill with you ideas below.
