// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"context"
	"time"

	"github.com/SupenBysz/gf-admin-community/sys_consts"
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
	"github.com/gogf/gf/v2/database/gdb"
)

// internalSysFileDao is internal type for wrapping internal DAO implements.
type internalSysFileDao = *internal.SysFileDao

// sysFileDao is the data access object for table sys_file.
// You can define custom methods on it to extend its functionality as you wish.
type sysFileDao struct {
	internalSysFileDao
}

var (
	// SysFile is globally public accessible object for table sys_file operations.
	SysFile = sysFileDao{
		internal.NewSysFileDao(),
	}
)

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *sysFileDao) Ctx(ctx context.Context, cacheOption ...gdb.CacheOption) *gdb.Model {
	conf := gdb.CacheOption{
		Duration: time.Hour * 24,
		Force:    false,
	}

	if len(cacheOption) == 0 {
		for _, cacheConf := range sys_consts.Global.OrmCacheConf {
			if cacheConf.TableName == dao.Table() {
				conf.Duration = time.Second * (time.Duration)(cacheConf.ExpireSeconds)
				conf.Force = cacheConf.Force
			}
		}
	} else {
		conf = cacheOption[0]
	}

	return dao.DB().Model(dao.Table()).Safe().Ctx(ctx).Cache(conf)
}
