// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_dao/internal"
)

// internalSysCasbinDao is internal type for wrapping internal DAO implements.
type internalSysCasbinDao = *internal.SysCasbinDao

// sysCasbinDao is the data access object for table sys_casbin.
// You can define custom methods on it to extend its functionality as you wish.
type sysCasbinDao struct {
	internalSysCasbinDao
}

var (
	// SysCasbin is globally public accessible object for table sys_casbin operations.
	SysCasbin = sysCasbinDao{
		internal.NewSysCasbinDao(),
	}
)

// Fill with you ideas below.
