// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/model"
)

type (
	ISdkBaidu interface {
		GetBaiduSdkConfToken(ctx context.Context, identifier string) (tokenInfo *model.BaiduSdkConfToken, err error)
		GetBaiduSdkConfList(ctx context.Context) (*[]model.BaiduSdkConf, error)
		GetBaiduSdkConf(ctx context.Context, identifier string) (*model.BaiduSdkConf, error)
		SaveBaiduSdkConf(ctx context.Context, info model.BaiduSdkConf, isCreate bool) (*model.BaiduSdkConf, error)
		DeleteBaiduSdkConf(ctx context.Context, identifier string) (bool, error)
		OCRBankCard(ctx context.Context, imageBase64 string) (*model.OCRBankCard, error)
		OCRIDCard(ctx context.Context, imageBase64 string, detectRisk string, idCardSide string) (*model.BaiduSdkOCRIDCard, error)
		OCRBusinessLicense(ctx context.Context, imageBase64 string) (*model.BusinessLicenseOCR, error)
	}
)

var (
	localSdkBaidu ISdkBaidu
)

func SdkBaidu() ISdkBaidu {
	if localSdkBaidu == nil {
		panic("implement not found for interface ISdkBaidu, forgot register?")
	}
	return localSdkBaidu
}

func RegisterSdkBaidu(i ISdkBaidu) {
	localSdkBaidu = i
}
