// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/model"
)

type (
	ISdkHuaWeiYun interface {
		GetHuaWeiYunSdkConfList(ctx context.Context) (*[]model.HuaWeiYunSdkConf, error)
		GetHuaWeiYunSdkConf(ctx context.Context, identifier string) (tokenInfo *model.HuaWeiYunSdkConf, err error)
		SaveHuaWeiYunSdkConf(ctx context.Context, info model.HuaWeiYunSdkConf, isCreate bool) (*model.HuaWeiYunSdkConf, error)
		DeleteHuaWeiYunSdkConf(ctx context.Context, identifier string) (bool, error)
	}
)

var (
	localSdkHuaWeiYun ISdkHuaWeiYun
)

func SdkHuaWeiYun() ISdkHuaWeiYun {
	if localSdkHuaWeiYun == nil {
		panic("implement not found for interface ISdkHuaWeiYun, forgot register?")
	}
	return localSdkHuaWeiYun
}

func RegisterSdkHuaWeiYun(i ISdkHuaWeiYun) {
	localSdkHuaWeiYun = i
}
