// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/api_v1/sysapi"
	"github.com/SupenBysz/gf-admin-community/model"
	"github.com/SupenBysz/gf-admin-community/model/entity"
)

type (
	ISysPermission interface {
		GetPermissionById(ctx context.Context, permissionId int64) (*entity.SysPermission, error)
		GetPermissionByName(ctx context.Context, permissionName string) (*entity.SysPermission, error)
		QueryPermissionList(ctx context.Context, info model.SearchFilter) (*sysapi.SysPermissionInfoListRes, error)
		GetPermissionList(ctx context.Context, parentId int64, IsRecursive bool) (*[]entity.SysPermission, error)
		GetPermissionTree(ctx context.Context, parentId int64) (*[]model.SysPermissionTree, error)
		CreatePermission(ctx context.Context, info model.SysPermission) (*entity.SysPermission, error)
		UpdatePermission(ctx context.Context, info model.SysPermission) (*entity.SysPermission, error)
		SavePermission(ctx context.Context, info model.SysPermission) (*entity.SysPermission, error)
		DeletePermission(ctx context.Context, permissionId int64) (bool, error)
	}
)

var (
	localSysPermission ISysPermission
)

func SysPermission() ISysPermission {
	if localSysPermission == nil {
		panic("implement not found for interface ISysPermission, forgot register?")
	}
	return localSysPermission
}

func RegisterSysPermission(i ISysPermission) {
	localSysPermission = i
}
