// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/SupenBysz/gf-admin-community/model/dao/internal"
)

// internalFdAccountBillDao is internal type for wrapping internal DAO implements.
type internalFdAccountBillDao = *internal.FdAccountBillDao

// fdAccountBillDao is the data access object for table fd_account_bill.
// You can define custom methods on it to extend its functionality as you wish.
type fdAccountBillDao struct {
	internalFdAccountBillDao
}

var (
	// FdAccountBill is globally public accessible object for table fd_account_bill operations.
	FdAccountBill = fdAccountBillDao{
		internal.NewFdAccountBillDao(),
	}
)

// Fill with you ideas below.
