// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/SupenBysz/gf-admin-community/model/dao/internal"
)

// internalFdCurrentyDao is internal type for wrapping internal DAO implements.
type internalFdCurrentyDao = *internal.FdCurrentyDao

// fdCurrentyDao is the data access object for table fd_currenty.
// You can define custom methods on it to extend its functionality as you wish.
type fdCurrentyDao struct {
	internalFdCurrentyDao
}

var (
	// FdCurrenty is globally public accessible object for table fd_currenty operations.
	FdCurrenty = fdCurrentyDao{
		internal.NewFdCurrentyDao(),
	}
)

// Fill with you ideas below.
