// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/SupenBysz/gf-admin-community/model/dao/internal"
)

// internalFdCurrencyDao is internal type for wrapping internal DAO implements.
type internalFdCurrencyDao = *internal.FdCurrencyDao

// fdCurrencyDao is the data access object for table fd_currency.
// You can define custom methods on it to extend its functionality as you wish.
type fdCurrencyDao struct {
	internalFdCurrencyDao
}

var (
	// FdCurrency is globally public accessible object for table fd_currency operations.
	FdCurrency = fdCurrencyDao{
		internal.NewFdCurrencyDao(),
	}
)

// Fill with you ideas below.
