// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/SupenBysz/gf-admin-community/model/dao/internal"
)

// internalFdInvoiceDao is internal type for wrapping internal DAO implements.
type internalFdInvoiceDao = *internal.FdInvoiceDao

// fdInvoiceDao is the data access object for table fd_invoice.
// You can define custom methods on it to extend its functionality as you wish.
type fdInvoiceDao struct {
	internalFdInvoiceDao
}

var (
	// FdInvoice is globally public accessible object for table fd_invoice operations.
	FdInvoice = fdInvoiceDao{
		internal.NewFdInvoiceDao(),
	}
)

// Fill with you ideas below.
