// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/SupenBysz/gf-admin-community/model/dao/internal"
)

// internalSysSmsLogsDao is internal type for wrapping internal DAO implements.
type internalSysSmsLogsDao = *internal.SysSmsLogsDao

// sysSmsLogsDao is the data access object for table sys_sms_logs.
// You can define custom methods on it to extend its functionality as you wish.
type sysSmsLogsDao struct {
	internalSysSmsLogsDao
}

var (
	// SysSmsLogs is globally public accessible object for table sys_sms_logs operations.
	SysSmsLogs = sysSmsLogsDao{
		internal.NewSysSmsLogsDao(),
	}
)

// Fill with you ideas below.
