// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/SupenBysz/gf-admin-community/model/dao/internal"
)

// internalSysAuditDao is internal type for wrapping internal DAO implements.
type internalSysAuditDao = *internal.SysAuditDao

// sysAuditDao is the data access object for table sys_audit.
// You can define custom methods on it to extend its functionality as you wish.
type sysAuditDao struct {
	internalSysAuditDao
}

var (
	// SysAudit is globally public accessible object for table sys_audit operations.
	SysAudit = sysAuditDao{
		internal.NewSysAuditDao(),
	}
)

// Fill with you ideas below.
