// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package sys_service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/sys_model"
	"github.com/SupenBysz/gf-admin-community/sys_model/sys_entity"
)

type (
	ISysMenu interface {
		GetMenuById(ctx context.Context, menuId int64) (*sys_entity.SysMenu, error)
		CreateMenu(ctx context.Context, info *sys_model.SysMenu) (*sys_entity.SysMenu, error)
		UpdateMenu(ctx context.Context, info *sys_model.SysMenu) (*sys_entity.SysMenu, error)
		SaveMenu(ctx context.Context, info *sys_model.SysMenu) (*sys_entity.SysMenu, error)
		DeleteMenu(ctx context.Context, id int64) (bool, error)
		MakeMenuTree(ctx context.Context, parentId int64, isMakeNodeFun func(ctx context.Context, cruuentMenu *sys_entity.SysMenu) bool) ([]*sys_model.SysMenuTreeRes, error)
		GetMenuTree(ctx context.Context, parentId int64) ([]*sys_model.SysMenuTreeRes, error)
		GetMenuList(ctx context.Context, parentId int64, IsRecursive bool, limitChildrenIds ...int64) ([]*sys_entity.SysMenu, error)
	}
)

var (
	localSysMenu ISysMenu
)

func SysMenu() ISysMenu {
	if localSysMenu == nil {
		panic("implement not found for interface ISysMenu, forgot register?")
	}
	return localSysMenu
}

func RegisterSysMenu(i ISysMenu) {
	localSysMenu = i
}
