// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package sys_service

import (
	"context"
)

type (
	ISysSms interface {
		Verify(ctx context.Context, mobile int64, captcha string, typeIdentifier ...string) (bool, error)
	}
)

var (
	localSysSms ISysSms
)

func SysSms() ISysSms {
	if localSysSms == nil {
		panic("implement not found for interface ISysSms, forgot register?")
	}
	return localSysSms
}

func RegisterSysSms(i ISysSms) {
	localSysSms = i
}
