// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package sys_service

type (
	ISysSms interface{}
)

var (
	localSysSms ISysSms
)

func SysSms() ISysSms {
	if localSysSms == nil {
		panic("implement not found for interface ISysSms, forgot register?")
	}
	return localSysSms
}

func RegisterSysSms(i ISysSms) {
	localSysSms = i
}
