// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package sys_service

import (
	"context"
)

type (
	ISessionError interface {
		Append(ctx context.Context, error error) error
		HasError(ctx context.Context, err error) (response bool)
		Iterator(ctx context.Context, f func(k int, err error) bool)
	}
)

var (
	localSessionError ISessionError
)

func SessionError() ISessionError {
	if localSessionError == nil {
		panic("implement not found for interface ISessionError, forgot register?")
	}
	return localSessionError
}

func RegisterSessionError(i ISessionError) {
	localSessionError = i
}
