// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsServiceProviderConfig is the golang structure of table sms_service_provider_config for DAO operations like Where/Data.
type SmsServiceProviderConfig struct {
	g.Meta          `orm:"table:sms_service_provider_config, do:true"`
	Id              interface{} // 渠道商id
	ProviderNo      interface{} // 渠道商编号
	ProviderName    interface{} // 渠道商名字
	AccessKeyId     interface{} // 身份标识
	AccessKeySecret interface{} // 身份认证密钥
	Endpoint        interface{} // 域名调用
	SdkAppId        interface{} // 应用id
	Region          interface{} // 地域
	Remark          interface{} // 备注
	Status          interface{} // 状态
	CreatedAt       *gtime.Time //
	UpdatedAt       *gtime.Time //
	DeletedAt       *gtime.Time //
}
