// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsSendLog is the golang structure of table sms_send_log for DAO operations like Where/Data.
type SmsSendLog struct {
	g.Meta      `orm:"table:sms_send_log, do:true"`
	Id          interface{} // ID
	AppNo       interface{} // 应用ID
	BusinessNo  interface{} // 业务编号
	Status      interface{} // 状态
	Fee         interface{} // 计价条数
	PhoneNumber interface{} // 发送手机号
	Message     interface{} // 接口响应消息
	Code        interface{} // 接口响应状态码
	Content     interface{} // 发送内容
	Remark      interface{} // 备注
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
	DeletedAt   *gtime.Time //
}
