// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsTemplateConfig is the golang structure of table sms_template_config for DAO operations like Where/Data.
type SmsTemplateConfig struct {
	g.Meta               `orm:"table:sms_template_config, do:true"`
	Id                   interface{} // ID
	SignName             interface{} // 签名名称
	TemplateNo           interface{} // 模版编号
	TemplateName         interface{} // 模版名称
	TemplateContent      interface{} // 模版内容
	ThirdPartyTemplateNo interface{} // 第三方模版编号
	ProviderNo           interface{} // 渠道商编号
	Remark               interface{} // 备注
	Status               interface{} // 状态: 0禁用 1正常
	AuditUserId          interface{} // 审核者UserID 审核者UserID
	AuditReplyMsg        interface{} // 审核回复，仅审核不通过时才有值
	AuditAt              interface{} // 审核时间
	CreatedAt            *gtime.Time //
	UpdatedAt            *gtime.Time //
	DeletedAt            *gtime.Time //
}
