// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsAppConfig is the golang structure of table sms_app_config for DAO operations like Where/Data.
type SmsAppConfig struct {
	g.Meta          `orm:"table:sms_app_config, do:true"`
	Id              interface{} // ID
	AppNo           interface{} // 应用编号
	AppName         interface{} // 应用名称
	AvailableNumber interface{} // 可用数量
	CurrentLimiting interface{} // 限流数量
	UseNumber       interface{} // 已用数量
	Remark          interface{} // 备注
	Status          interface{} // 状态: 0禁用 1正常
	CreatedAt       *gtime.Time //
	UpdatedAt       *gtime.Time //
	DeletedAt       *gtime.Time //
}
