// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsBusinessConfig is the golang structure of table sms_business_config for DAO operations like Where/Data.
type SmsBusinessConfig struct {
	g.Meta       `orm:"table:sms_business_config, do:true"`
	Id           interface{} // ID
	AppNo        interface{} // 应用ID
	BusinessName interface{} // 业务名称
	BusinessNo   interface{} // 业务编号
	TemplateNo   interface{} // 模版编号
	BusinessDesc interface{} // 业务说明
	Remark       interface{} // 备注
	Status       interface{} // 状态: 0禁用 1正常
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
	DeletedAt    *gtime.Time //
}
