// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysCasbin is the golang structure of table sys_casbin for DAO operations like Where/Data.
type SysCasbin struct {
	g.Meta `orm:"table:sys_casbin, do:true"`
	Ptype  interface{} //
	V0     interface{} //
	V1     interface{} //
	V2     interface{} //
	V3     interface{} //
	V4     interface{} //
	V5     interface{} //
}
