// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdAccount is the golang structure for table fd_account.
type FdAccount struct {
	Id                 int64       `json:"id"                 description:"ID"`
	Name               string      `json:"name"               description:"账户名称"`
	UnionLicenseId     int64       `json:"unionLicenseId"     description:"关联资质ID，大于0时必须保值与 union_user_id 关联得上"`
	UnionUserId        int64       `json:"unionUserId"        description:"关联用户ID"`
	CurrencyCode       string      `json:"currencyCode"       description:"货币代码"`
	IsEnabled          int         `json:"isEnabled"          description:"是否启用：1启用，0禁用"`
	LimitState         int         `json:"limitState"         description:"限制状态：0不限制，1限制支出、2限制收入"`
	PrecisionOfBalance int         `json:"precisionOfBalance" description:"货币单位精度：1:元，10:角，100:分，1000:厘，10000:毫，……"`
	Balance            int64       `json:"balance"            description:"当前余额，必须要与账单最后一笔交易余额对应得上"`
	CreatedAt          *gtime.Time `json:"createdAt"          description:""`
	UpdatedAt          *gtime.Time `json:"updatedAt"          description:""`
	DeletedAt          *gtime.Time `json:"deletedAt"          description:""`
}
