// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// FdCurrenty is the golang structure for table fd_currenty.
type FdCurrenty struct {
	Code          string `json:"code"          description:"国家编码"`
	EnName        string `json:"enName"        description:"国家英文名称"`
	CnName        string `json:"cnName"        description:"国家中文名称"`
	CurrencyCode  string `json:"currencyCode"  description:"货币编码"`
	CurrencyCn    string `json:"currencyCn"    description:"货币中文名称"`
	CurrencyEn    string `json:"currencyEn"    description:"货币英文名称"`
	Symbol        string `json:"symbol"        description:"货币符号"`
	SymbolNative  string `json:"symbolNative"  description:"货币原生符号"`
	IsLegalTender int    `json:"isLegalTender" description:"是否法定货币：1是，0否"`
}
