// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdInvoice is the golang structure for table fd_invoice.
type FdInvoice struct {
	Id             int64       `json:"id"             description:""`
	Name           string      `json:"name"           description:"发票抬头名称"`
	TaxId          string      `json:"taxId"          description:"纳税识别号"`
	Addr           string      `json:"addr"           description:"发票收件地址，限纸质"`
	Email          string      `json:"email"          description:"发票收件邮箱，限电子发票"`
	UserId         int64       `json:"userId"         description:"申请人UserID"`
	AuditUserId    int64       `json:"auditUserId"    description:"审核人UserID"`
	AuditReplayMsg string      `json:"auditReplayMsg" description:"审核回复，仅审核不通过时才有值"`
	AuditAt        *gtime.Time `json:"auditAt"        description:"审核时间"`
	State          int         `json:"state"          description:"状态：1待审核、2已通过、3不通过"`
	CreatedAt      *gtime.Time `json:"createdAt"      description:""`
	UpdatedAt      *gtime.Time `json:"updatedAt"      description:""`
	DeletedAt      *gtime.Time `json:"deletedAt"      description:""`
}
