// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FdInvoiceDetail is the golang structure for table fd_invoice_detail.
type FdInvoiceDetail struct {
	Id            int64       `json:"id"            description:"ID"`
	TaxNumber     string      `json:"taxNumber"     description:"纳税识别号"`
	TaxName       string      `json:"taxName"       description:"纳税人名称"`
	BillIds       string      `json:"billIds"       description:"账单ID组"`
	Amount        int64       `json:"amount"        description:"开票金额，单位精度：分"`
	Rate          int         `json:"rate"          description:"税率，如3% 则填入3"`
	RateMount     int64       `json:"rateMount"     description:"税额，单位精度：分"`
	Remark        string      `json:"remark"        description:"发布内容描述"`
	Type          int         `json:"type"          description:"发票类型：1电子发票，2纸质发票"`
	State         int         `json:"state"         description:"状态：1待审核、2待开票、4开票失败、8已开票、16已撤销"`
	AuditUserIds  int64       `json:"auditUserIds"  description:"审核者UserID，多个用逗号隔开"`
	MakeType      int         `json:"makeType"      description:"出票类型：1普通发票、2增值税专用发票、3专业发票"`
	MakeUserId    int64       `json:"makeUserId"    description:"出票人UserID，如果是系统出票则默认-1"`
	MakeAt        *gtime.Time `json:"makeAt"        description:"出票时间"`
	CourierName   string      `json:"courierName"   description:"快递名称"`
	CourierNumber string      `json:"courierNumber" description:"快递编号"`
	FdInvoiceId   int64       `json:"fdInvoiceId"   description:"发票抬头ID"`
	AuditUserId   int64       `json:"auditUserId"   description:"审核者UserID"`
	AuditReplyMsg string      `json:"auditReplyMsg" description:"审核回复，仅审核不通过时才有值"`
	AuditAt       *gtime.Time `json:"auditAt"       description:"审核时间"`
	CreatedAt     *gtime.Time `json:"createdAt"     description:""`
	UpdatedAt     *gtime.Time `json:"updatedAt"     description:""`
	DeletedAt     *gtime.Time `json:"deletedAt"     description:""`
}
