// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SchemaMigrations is the golang structure for table schema_migrations.
type SchemaMigrations struct {
	Version int64 `json:"version" description:""`
	Dirty   bool  `json:"dirty"   description:""`
}
